const WorkJournal = require('../models/WorkJournal');

/**
 * Auto-creates a verified Work Journal entry when a Certificate is registered
 */
const syncCertificateEvidence = async (cert) => {
  try {
    if (!cert || !cert.employeeId) return;

    // Check if evidence already exists for this certificate
    const existing = await WorkJournal.findOne({
      employeeId: cert.employeeId,
      sourceType: 'Certification',
      sourceId: cert._id
    });

    if (existing) {
      existing.title = `Earned Verified Certification: ${cert.name}`;
      existing.businessImpact = `Accredited by ${cert.issuer}. Added to professional skill repository.`;
      existing.evidenceUrl = cert.fileUrl || '';
      existing.completedDate = cert.issueDate || Date.now();
      await existing.save();
      return existing;
    }

    const journal = await WorkJournal.create({
      employeeId: cert.employeeId,
      title: `Earned Verified Certification: ${cert.name}`,
      project: 'Professional Development',
      client: cert.issuer || 'Accrediting Body',
      category: 'Certification',
      description: `Earned professional credential "${cert.name}" issued by ${cert.issuer}.`,
      businessImpact: `Verified skill accreditation from ${cert.issuer}.`,
      evidenceType: 'PDF',
      evidenceUrl: cert.fileUrl || '',
      completedDate: cert.issueDate || Date.now(),
      tags: ['Certification', cert.issuer, 'Verified Skill'],
      impactScore: 'High',
      evidenceWeight: 'Medium',
      status: 'approved', // Auto-verified system evidence
      autoGenerated: true,
      sourceType: 'Certification',
      sourceId: cert._id,
      managerFeedback: 'Auto-verified system credential'
    });

    return journal;
  } catch (err) {
    console.error('syncCertificateEvidence error:', err);
  }
};

/**
 * Auto-creates a verified Work Journal entry when an Award/Recognition is granted
 */
const syncAwardEvidence = async (recognition) => {
  try {
    if (!recognition || !recognition.recipientId) return;

    const existing = await WorkJournal.findOne({
      employeeId: recognition.recipientId,
      sourceType: 'Award',
      sourceId: recognition._id
    });

    if (existing) {
      existing.title = `Awarded: ${recognition.title || 'Excellence Recognition'}`;
      existing.description = recognition.citation || recognition.reason || '';
      await existing.save();
      return existing;
    }

    const journal = await WorkJournal.create({
      employeeId: recognition.recipientId,
      title: `Awarded: ${recognition.title || 'Excellence Recognition'}`,
      project: 'Corporate Recognition',
      client: 'Internal Honors Desk',
      category: 'Recognition',
      description: recognition.citation || recognition.reason || 'Granted official company accolade.',
      businessImpact: `Recognized for outstanding contribution: ${recognition.badgeType || 'Excellence'}.`,
      evidenceType: 'System Sync',
      completedDate: recognition.createdAt || Date.now(),
      tags: ['Award', recognition.badgeType || 'Honor', 'Excellence'],
      impactScore: 'Critical',
      evidenceWeight: 'Very High',
      status: 'approved', // Auto-verified system evidence
      autoGenerated: true,
      sourceType: 'Award',
      sourceId: recognition._id,
      managerFeedback: 'Auto-verified corporate recognition award'
    });

    return journal;
  } catch (err) {
    console.error('syncAwardEvidence error:', err);
  }
};

/**
 * Auto-creates a verified Work Journal entry when a Promotion is approved
 */
const syncPromotionEvidence = async (promotion) => {
  try {
    if (!promotion || !promotion.employeeId) return;

    const existing = await WorkJournal.findOne({
      employeeId: promotion.employeeId,
      sourceType: 'Promotion',
      sourceId: promotion._id
    });

    if (existing) return existing;

    const journal = await WorkJournal.create({
      employeeId: promotion.employeeId,
      title: `Career Growth: Promoted to New Role`,
      project: 'Career Progression',
      client: 'Leadership Board',
      category: 'Career Growth',
      description: `Promoted for high-impact performance & sustained business output.`,
      businessImpact: `Elevated to higher organizational tier based on merit and proven metrics.`,
      evidenceType: 'System Sync',
      completedDate: promotion.effectiveDate || Date.now(),
      tags: ['Promotion', 'Career Growth', 'Merit'],
      impactScore: 'Critical',
      evidenceWeight: 'Very High',
      status: 'approved',
      autoGenerated: true,
      sourceType: 'Promotion',
      sourceId: promotion._id,
      managerFeedback: 'Auto-verified career progression milestone'
    });

    return journal;
  } catch (err) {
    console.error('syncPromotionEvidence error:', err);
  }
};

module.exports = {
  syncCertificateEvidence,
  syncAwardEvidence,
  syncPromotionEvidence
};
